window.IMOVEIS = [
  {
    id: 1,
    referencia: "CI-001",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Residencial Mariana",
    localizacao: "Apt. 401 bloco 04",
    cidade: "Goianésia",
    preco: 1300,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 1,
    area: 55,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/001/01.jpeg",
    fotos: ["images/imoveis/001/01.jpeg"],
    data: "2026-08-01",
    descricao: "Apartamento localizado no Residencial Mariana, com 2 quartos e 1 banheiro. Ambiente confortável e bem localizado para moradia.",
    disponivel: true
  },
  {
    id: 2,
    referencia: "CI-002",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Residencial Mariana",
    localizacao: "Apt. 204 bloco 11",
    cidade: "Goianésia",
    preco: 1300,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 1,
    area: 55,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/002/01.jpeg",
    fotos: ["images/imoveis/002/01.jpeg"],
    data: "2026-07-10",
    descricao: "Apartamento no Residencial Mariana, 2 quartos e 1 banheiro, ideal para famílias que buscam conforto e segurança.",
    disponivel: true
  },
  {
    id: 3,
    referencia: "CI-003",
    titulo: "Aluguel – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Aluguel",
    bairro: "Setor Universitário",
    localizacao: "Rua 14, n° 444",
    cidade: "Goianésia",
    preco: 2300,
    quartos: 3,
    suites: 0,
    banheiros: 3,
    garagem: 2,
    area: 180,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/003/01.jpeg",
    fotos: ["images/imoveis/003/01.jpeg"],
    data: "2026-07-16",
    descricao: "Casa espaçosa com 3 quartos e 3 banheiros no Setor Universitário. Ótima localização e área ampla.",
    disponivel: true
  },
  {
    id: 4,
    referencia: "CI-004",
    titulo: "Aluguel – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Aluguel",
    bairro: "Residencial Ipê",
    localizacao: "Rua Zico Fraga, Qd. 40 Lt. 09",
    cidade: "Goianésia",
    preco: 1100,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 1,
    area: 100,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/004/01.jpeg",
    fotos: ["images/imoveis/004/01.jpeg"],
    data: "2026-07-17",
    descricao: "Casa aconchegante no Residencial Ipê, com 2 quartos e 1 banheiro. Ótima opção para quem busca tranquilidade.",
    disponivel: true
  },
  {
    id: 5,
    referencia: "CI-005",
    titulo: "Aluguel – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Aluguel",
    bairro: "Setor Sul",
    localizacao: "Rua 37, n° 540",
    cidade: "Goianésia",
    preco: 2700,
    quartos: 4,
    suites: 0,
    banheiros: 3,
    garagem: 2,
    area: 220,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/005/01.jpeg",
    fotos: ["images/imoveis/005/01.jpeg"],
    data: "2026-07-21",
    descricao: "Casa ampla no Setor Sul com 4 quartos e 3 banheiros. Perfeita para famílias que necessitam de espaço e conforto.",
    disponivel: true
  },
  {
    id: 6,
    referencia: "CI-006",
    titulo: "Aluguel – Galpão",
    categoria: "Comercial",
    tipo: "Galpão",
    status: "Aluguel",
    bairro: "Palmeiras",
    localizacao: "Av. Alameda Otávio Lage, 01",
    cidade: "Goianésia",
    preco: 4500,
    quartos: 0,
    suites: 0,
    banheiros: 3,
    garagem: 0,
    area: 500,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/006/01.jpeg",
    fotos: ["images/imoveis/006/01.jpeg"],
    data: "2026-07-18",
    descricao: "Galpão comercial na Avenida Alameda Otávio Lage, com grande área útil, ideal para indústria, comércio ou estoque.",
    disponivel: true
  },
  {
    id: 7,
    referencia: "CI-007",
    titulo: "Aluguel – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Aluguel",
    bairro: "Nestor Ville",
    localizacao: "Rua Dona Cida, Qd. 12 Lt. 09",
    cidade: "Goianésia",
    preco: 1400,
    quartos: 2,
    suites: 0,
    banheiros: 2,
    garagem: 1,
    area: 120,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/007/01.jpeg",
    fotos: ["images/imoveis/007/01.jpeg"],
    data: "2026-07-29",
    descricao: "Casa no Nestor Ville com 2 quartos e 2 banheiros. Bairro calmo e familiar, ideal para moradia.",
    disponivel: true
  },
  {
    id: 8,
    referencia: "CI-008",
    titulo: "Aluguel – Galpão",
    categoria: "Comercial",
    tipo: "Galpão",
    status: "Aluguel",
    bairro: "",
    localizacao: "Av. Laurentino Martins, n° 2.575 Qd. 28 Lt. 14",
    cidade: "Goianésia",
    preco: 4052.5,
    quartos: 0,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 450,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/008/01.jpeg",
    fotos: ["images/imoveis/008/01.jpeg"],
    data: "2026-07-30",
    descricao: "Galpão na Avenida Laurentino Martins, excelente localização e ótimo espaço para atividades comerciais ou industriais.",
    disponivel: true
  },
  {
    id: 9,
    referencia: "CI-009",
    titulo: "Aluguel – Kit net",
    categoria: "Residencial",
    tipo: "Kitnet",
    status: "Aluguel",
    bairro: "Centro",
    localizacao: "Rua 29, n° 365",
    cidade: "Goianésia",
    preco: 700,
    quartos: 1,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 35,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/009/01.jpeg",
    fotos: ["images/imoveis/009/01.jpeg"],
    data: "2026-07-30",
    descricao: "Kitnet no Centro de Goianésia, em frente ao escritório da Caetano Imóveis. Prática, mobiliada e perto de tudo.",
    disponivel: true
  },
  {
    id: 10,
    referencia: "CI-010",
    titulo: "Aluguel – Kit net",
    categoria: "Residencial",
    tipo: "Kitnet",
    status: "Aluguel",
    bairro: "Palmeiras 3",
    localizacao: "Rua Meriti, Qd. 08 Lt. 22",
    cidade: "Goianésia",
    preco: 800,
    quartos: 1,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 38,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/010/01.jpeg",
    fotos: ["images/imoveis/010/01.jpeg"],
    data: "2026-07-31",
    descricao: "Kitnet no Bairro Palmeiras 3, 1 quarto e 1 banheiro. Ótimo custo-benefício para quem busca praticidade.",
    disponivel: true
  },
  {
    id: 11,
    referencia: "CI-011",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Setor Universitário",
    localizacao: "Rua 21, 441",
    cidade: "Goianésia",
    preco: 2500,
    quartos: 2,
    suites: 0,
    banheiros: 2,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/011/01.jpeg",
    fotos: ["images/imoveis/011/01.jpeg"],
    data: "",
    descricao: "Apartamento no Setor Universitário com 2 quartos e 2 banheiros, em ótima localização e pronto para morar.",
    disponivel: true
  },
  {
    id: 12,
    referencia: "CI-012",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Residencial Mariana",
    localizacao: "Apt. 103 bloco 07",
    cidade: "Goianésia",
    preco: 800,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/012/01.jpeg",
    fotos: ["images/imoveis/012/01.jpeg"],
    data: "",
    descricao: "Apartamento no Residencial Mariana, 2 quartos e 1 banheiro, ótima oportunidade com excelente custo-benefício.",
    disponivel: true
  },
  {
    id: 13,
    referencia: "CI-013",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Residencial Mariana",
    localizacao: "Apt. 401 bloco 13",
    cidade: "Goianésia",
    preco: 1350,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/013/01.jpeg",
    fotos: ["images/imoveis/013/01.jpeg"],
    data: "",
    descricao: "Apartamento no Residencial Mariana com 2 quartos e 1 banheiro. Conforto e praticidade para você e sua família.",
    disponivel: true
  },
  {
    id: 14,
    referencia: "CI-014",
    titulo: "Aluguel – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Aluguel",
    bairro: "Setor Sul",
    localizacao: "Rua 08, n° 305",
    cidade: "Goianésia",
    preco: 1800,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/014/01.jpeg",
    fotos: ["images/imoveis/014/01.jpeg"],
    data: "",
    descricao: "Casa no Setor Sul com 3 quartos e 2 banheiros. Espaço ideal para quem busca conforto e boa localização.",
    disponivel: true
  },
  {
    id: 15,
    referencia: "CI-015",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Centro",
    localizacao: "Rua 29, n° 412, apt. 02",
    cidade: "Goianésia",
    preco: 1700,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/015/01.jpeg",
    fotos: ["images/imoveis/015/01.jpeg"],
    data: "",
    descricao: "Apartamento no Centro de Goianésia com 2 quartos e 1 banheiro, perto de comércio e serviços.",
    disponivel: true
  },
  {
    id: 16,
    referencia: "CI-016",
    titulo: "Aluguel – Ponto/Casa",
    categoria: "Comercial",
    tipo: "Ponto Comercial",
    status: "Aluguel",
    bairro: "Centro",
    localizacao: "Rua 29, n° 374",
    cidade: "Goianésia",
    preco: 1800,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/016/01.jpeg",
    fotos: ["images/imoveis/016/01.jpeg"],
    data: "",
    descricao: "Ponto comercial com casa no Centro de Goianésia, ideal para quem deseja morar e trabalhar no mesmo local.",
    disponivel: true
  },
  {
    id: 17,
    referencia: "CI-017",
    titulo: "Aluguel – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Aluguel",
    bairro: "Nova Aurora",
    localizacao: "Av. Contorno, n° 89",
    cidade: "Goianésia",
    preco: 2000,
    quartos: 3,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/017/01.jpeg",
    fotos: ["images/imoveis/017/01.jpeg"],
    data: "",
    descricao: "Casa no Bairro Nova Aurora com 3 quartos e 1 banheiro. Ótima opção para locação em localização privilegiada.",
    disponivel: true
  },
  {
    id: 18,
    referencia: "CI-018",
    titulo: "Aluguel – Kitnet",
    categoria: "Residencial",
    tipo: "Kitnet",
    status: "Aluguel",
    bairro: "Residencial Granville",
    localizacao: "Rua Jaraguá, n° 31 Qd. 17 Lt. 08",
    cidade: "Goianésia",
    preco: 880,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/018/01.jpeg",
    fotos: ["images/imoveis/018/01.jpeg"],
    data: "",
    descricao: "Kitnet no Residencial Granville com 2 quartos e 1 banheiro. Prática, moderna e em ótimo bairro.",
    disponivel: true
  },
  {
    id: 19,
    referencia: "CI-019",
    titulo: "Aluguel – Kitnet",
    categoria: "Residencial",
    tipo: "Kitnet",
    status: "Aluguel",
    bairro: "Carrilho",
    localizacao: "Rua 25, n° 262, kitnet 06",
    cidade: "Goianésia",
    preco: 800,
    quartos: 1,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/019/01.jpeg",
    fotos: ["images/imoveis/019/01.jpeg"],
    data: "",
    descricao: "Kitnet no Bairro Carrilho com 1 quarto e 1 banheiro, perfeita para quem busca praticidade e economia.",
    disponivel: true
  },
  {
    id: 20,
    referencia: "CI-020",
    titulo: "Aluguel – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Aluguel",
    bairro: "Aldeia do Morro",
    localizacao: "Rua Pinheiro, n° 227",
    cidade: "Goianésia",
    preco: 1000,
    quartos: 2,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/020/01.jpeg",
    fotos: ["images/imoveis/020/01.jpeg"],
    data: "",
    descricao: "Casa na Aldeia do Morro com 2 quartos e 2 banheiros, em bairro tranquilo e bem localizado.",
    disponivel: true
  },
  {
    id: 21,
    referencia: "CI-021",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Setor Sul",
    localizacao: "Av. Goiás, nº 1231",
    cidade: "Goianésia",
    preco: 1700,
    quartos: 1,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/021/01.jpeg",
    fotos: ["images/imoveis/021/01.jpeg"],
    data: "",
    descricao: "Apartamento na Avenida Goiás, Setor Sul, com 1 quarto e 2 banheiros. Excelente localização.",
    disponivel: true
  },
  {
    id: 22,
    referencia: "CI-022",
    titulo: "Aluguel – Espaço",
    categoria: "Comercial",
    tipo: "Sala",
    status: "Aluguel",
    bairro: "",
    localizacao: "Barro Alto - GO",
    cidade: "Barro Alto",
    preco: 2824,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/022/01.jpg",
    fotos: ["images/imoveis/022/01.jpg"],
    data: "",
    descricao: "Espaço para locação em Barro Alto - GO, ideal para eventos, comércio ou outras atividades.",
    disponivel: true
  },
  {
    id: 23,
    referencia: "CI-023",
    titulo: "Aluguel – Espaço",
    categoria: "Comercial",
    tipo: "Sala",
    status: "Aluguel",
    bairro: "",
    localizacao: "Barro Alto - GO",
    cidade: "Barro Alto",
    preco: 4500,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/023/01.jpg",
    fotos: ["images/imoveis/023/01.jpg"],
    data: "",
    descricao: "Espaço amplo para locação em Barro Alto - GO, com ótima estrutura para diversos usos.",
    disponivel: true
  },
  {
    id: 24,
    referencia: "CI-024",
    titulo: "Aluguel – Área",
    categoria: "Terreno",
    tipo: "Área",
    status: "Aluguel",
    bairro: "Muniz Falcão",
    localizacao: "Rua 22, entre as ruas 45 e 49",
    cidade: "Goianésia",
    preco: 6072,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/024/01.jpeg",
    fotos: ["images/imoveis/024/01.jpeg"],
    data: "",
    descricao: "Área para locação na Rua 22, entre as ruas 45 a 49, Muniz Falcão. Perfeita para atividades comerciais.",
    disponivel: true
  },
  {
    id: 25,
    referencia: "CI-025",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Centro",
    localizacao: "Av. Goiás, nº 1.231",
    cidade: "Goianésia",
    preco: 1800,
    quartos: 1,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/025/01.jpeg",
    fotos: ["images/imoveis/025/01.jpeg"],
    data: "",
    descricao: "Apartamento na Avenida Goiás, Centro, com 1 quarto e 1 banheiro. Localização central e prática.",
    disponivel: true
  },
  {
    id: 26,
    referencia: "CI-026",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Setor Sul",
    localizacao: "Rua 31, nº 487",
    cidade: "Goianésia",
    preco: 1650,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/026/01.jpeg",
    fotos: ["images/imoveis/026/01.jpeg"],
    data: "",
    descricao: "Apartamento na Rua 31, Setor Sul, nº 487, com 2 quartos e 1 banheiro. Ótima localização.",
    disponivel: true
  },
  {
    id: 27,
    referencia: "CI-027",
    titulo: "Aluguel – Galpão",
    categoria: "Comercial",
    tipo: "Galpão",
    status: "Aluguel",
    bairro: "",
    localizacao: "Rua 34",
    cidade: "Goianésia",
    preco: 2800,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/027/01.jpeg",
    fotos: ["images/imoveis/027/01.jpeg"],
    data: "",
    descricao: "Galpão na Rua 34, ideal para comércio, indústria ou estoque em Goianésia.",
    disponivel: true
  },
  {
    id: 28,
    referencia: "CI-028",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Palmeiras 2",
    localizacao: "Rua Jequitibá, Qd. 31, Lt. 8/9",
    cidade: "Goianésia",
    preco: 1500,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/028/01.jpeg",
    fotos: ["images/imoveis/028/01.jpeg"],
    data: "",
    descricao: "Apartamento no Residencial Lopes, Palmeiras 2, com 2 quartos e 1 banheiro, em área tranquila.",
    disponivel: true
  },
  {
    id: 29,
    referencia: "CI-029",
    titulo: "Aluguel – Comercial",
    categoria: "Comercial",
    tipo: "Ponto Comercial",
    status: "Aluguel",
    bairro: "Centro",
    localizacao: "Rua 29, 402",
    cidade: "Goianésia",
    preco: 4000,
    quartos: 0,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/029/01.jpeg",
    fotos: ["images/imoveis/029/01.jpeg"],
    data: "",
    descricao: "Imóvel comercial no Centro de Goianésia, na Rua 29, com excelente ponto para o seu negócio.",
    disponivel: true
  },
  {
    id: 30,
    referencia: "CI-030",
    titulo: "Aluguel – Comercial",
    categoria: "Comercial",
    tipo: "Ponto Comercial",
    status: "Aluguel",
    bairro: "Centro",
    localizacao: "Rua 33",
    cidade: "Goianésia",
    preco: 3242,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/030/01.jpeg",
    fotos: ["images/imoveis/030/01.jpeg"],
    data: "",
    descricao: "Imóvel comercial na Rua 33, Centro de Goianésia. Ótima oportunidade para comércio.",
    disponivel: true
  },
  {
    id: 31,
    referencia: "CI-031",
    titulo: "Galpão para Oficina no Gaiola",
    categoria: "Comercial",
    tipo: "Galpão",
    status: "Aluguel",
    bairro: "Gaiola",
    localizacao: "Souzalândia - GO",
    cidade: "Souzalândia",
    preco: 1400,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/031/01.jpg",
    fotos: ["images/imoveis/031/01.jpg"],
    data: "",
    descricao: "Galpão para oficina no Gaiola, Souzalândia - GO. Ideal para mecânicas e serviços.",
    disponivel: true
  },
  {
    id: 32,
    referencia: "CI-032",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Porto Seguro",
    localizacao: "Bloco D, Apt. 202",
    cidade: "Goianésia",
    preco: 1600,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/032/01.jpeg",
    fotos: ["images/imoveis/032/01.jpeg"],
    data: "",
    descricao: "Apartamento no Condomínio Porto Seguro, Bloco D, com 2 quartos e 1 banheiro. Segurança e conforto.",
    disponivel: true
  },
  {
    id: 33,
    referencia: "CI-033",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Porto Seguro",
    localizacao: "Bloco A, Apt. 304",
    cidade: "Goianésia",
    preco: 1900,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/033/01.jpeg",
    fotos: ["images/imoveis/033/01.jpeg"],
    data: "",
    descricao: "Apartamento no Condomínio Porto Seguro, Bloco A, com 2 quartos e 1 banheiro. Estrutura completa.",
    disponivel: true
  },
  {
    id: 34,
    referencia: "CI-034",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Boulevard",
    localizacao: "Bloco B, Apt. 404",
    cidade: "Goianésia",
    preco: 1621,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/034/01.jpeg",
    fotos: ["images/imoveis/034/01.jpeg"],
    data: "",
    descricao: "Apartamento no Condomínio Boulevard, Bloco B, com 2 quartos e 1 banheiro. Moderno e bem localizado.",
    disponivel: true
  },
  {
    id: 35,
    referencia: "CI-035",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Setor Sul",
    localizacao: "Av. Goiás, nº 1231, apt. 02",
    cidade: "Goianésia",
    preco: 1800,
    quartos: 1,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/035/01.jpeg",
    fotos: ["images/imoveis/035/01.jpeg"],
    data: "",
    descricao: "Apartamento na Avenida Goiás, Setor Sul, com 1 quarto e 2 banheiros. Localização central.",
    disponivel: true
  },
  {
    id: 36,
    referencia: "CI-036",
    titulo: "Aluguel – Galpão",
    categoria: "Comercial",
    tipo: "Galpão",
    status: "Aluguel",
    bairro: "Carrilho",
    localizacao: "Rua 29, nº 195",
    cidade: "Goianésia",
    preco: 1500,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/036/01.jpeg",
    fotos: ["images/imoveis/036/01.jpeg"],
    data: "",
    descricao: "Galpão na Rua 29, Bairro Carrilho, entre as ruas 34 e 36. Bom espaço para diversos usos.",
    disponivel: true
  },
  {
    id: 37,
    referencia: "CI-037",
    titulo: "Aluguel – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Aluguel",
    bairro: "Parque das Palmeiras 3",
    localizacao: "Rua Jussara, nº 17",
    cidade: "Goianésia",
    preco: 1621,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/037/01.jpeg",
    fotos: ["images/imoveis/037/01.jpeg"],
    data: "",
    descricao: "Casa no Parque das Palmeiras 3, com 3 quartos e 2 banheiros. Ótima opção para famílias.",
    disponivel: true
  },
  {
    id: 38,
    referencia: "CI-038",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Centro",
    localizacao: "Rua 12, entre Av. Goiás e Rua 29",
    cidade: "Goianésia",
    preco: 2200,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/038/01.jpeg",
    fotos: ["images/imoveis/038/01.jpeg"],
    data: "",
    descricao: "Apartamento na Rua 12, entre Av. Goiás e Rua 29, com 3 quartos e 2 banheiros. Amplo e bem localizado.",
    disponivel: true
  },
  {
    id: 39,
    referencia: "CI-039",
    titulo: "Aluguel – Galpão",
    categoria: "Comercial",
    tipo: "Galpão",
    status: "Aluguel",
    bairro: "Palmeiras 2",
    localizacao: "Av. Brasil",
    cidade: "Goianésia",
    preco: 5500,
    quartos: 0,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/039/01.jpeg",
    fotos: ["images/imoveis/039/01.jpeg"],
    data: "",
    descricao: "Galpão na Avenida Brasil, Palmeiras 2, com grande área. Ideal para indústria ou comércio.",
    disponivel: true
  },
  {
    id: 40,
    referencia: "CI-040",
    titulo: "Aluguel – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Aluguel",
    bairro: "Centro",
    localizacao: "Rua 10, esquina com Av. Mato Grosso",
    cidade: "Goianésia",
    preco: 2500,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/040/01.jpeg",
    fotos: ["images/imoveis/040/01.jpeg"],
    data: "",
    descricao: "Apartamento na Rua 10, esquina com Av. Mato Grosso, com 3 quartos e 2 banheiros. Localização central.",
    disponivel: true
  },
  {
    id: 41,
    referencia: "CI-041",
    titulo: "Venda – Chácara",
    categoria: "Rural",
    tipo: "Chácara",
    status: "Venda",
    bairro: "",
    localizacao: "26 km de Goianésia - Souzalândia",
    cidade: "Souzalândia",
    preco: 1000000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/041/01.jpeg",
    fotos: ["images/imoveis/041/01.jpeg"],
    data: "",
    descricao: "Chácara a 26 km de Goianésia, em Souzalândia, com 3 quartos e 2 banheiros. Ótimo para descanso e lazer.",
    disponivel: true
  },
  {
    id: 42,
    referencia: "CI-042",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Palmeiras 2",
    localizacao: "",
    cidade: "Goianésia",
    preco: 370000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/042/01.jpeg",
    fotos: ["images/imoveis/042/01.jpeg"],
    data: "",
    descricao: "Casa no Bairro Palmeiras 2, com 3 quartos e 2 banheiros. Ótima oportunidade para investir.",
    disponivel: true
  },
  {
    id: 43,
    referencia: "CI-043",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Carrilho",
    localizacao: "Rua 35, nº 259",
    cidade: "Goianésia",
    preco: 500000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/043/01.jpeg",
    fotos: ["images/imoveis/043/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 35, Bairro Carrilho, com 3 quartos e 2 banheiros. Bem localizada.",
    disponivel: true
  },
  {
    id: 44,
    referencia: "CI-044",
    titulo: "Venda – 2 Lotes",
    categoria: "Terreno",
    tipo: "Lote",
    status: "Venda",
    bairro: "Granville",
    localizacao: "Av. Principal com Rua 07",
    cidade: "Goianésia",
    preco: 275000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/044/01.jpeg",
    fotos: ["images/imoveis/044/01.jpeg"],
    data: "",
    descricao: "2 lotes no Setor Granville, na Avenida Principal com a Rua 07. Excelente localização para construir.",
    disponivel: true
  },
  {
    id: 45,
    referencia: "CI-045",
    titulo: "Casa – Venda",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "",
    localizacao: "Rua Enomia Machado, nº 11",
    cidade: "Cirilândia",
    preco: 600000,
    quartos: 4,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/045/01.jpeg",
    fotos: ["images/imoveis/045/01.jpeg"],
    data: "",
    descricao: "Casa em Cirilândia, na Rua Enomia Machado, nº 11, com 4 quartos e 2 banheiros. Amplo imóvel.",
    disponivel: true
  },
  {
    id: 46,
    referencia: "CI-046",
    titulo: "Venda – Lotes",
    categoria: "Terreno",
    tipo: "Lote",
    status: "Venda",
    bairro: "Palmeiras",
    localizacao: "Rua Bacuri, Qd. 25, Lt. 05 a 07",
    cidade: "Goianésia",
    preco: 190000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/046/01.jpeg",
    fotos: ["images/imoveis/046/01.jpeg"],
    data: "",
    descricao: "Lotes na Rua Bacuri, Quadra 25, Lotes 05 a 07, no Bairro Palmeiras. Ótimo para investimento.",
    disponivel: true
  },
  {
    id: 47,
    referencia: "CI-047",
    titulo: "Venda – Chácara",
    categoria: "Rural",
    tipo: "Chácara",
    status: "Venda",
    bairro: "Recanto da Mata",
    localizacao: "3 km de Goianésia",
    cidade: "Goianésia",
    preco: 1000000,
    quartos: 5,
    suites: 0,
    banheiros: 7,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/047/01.jpeg",
    fotos: ["images/imoveis/047/01.jpeg"],
    data: "",
    descricao: "Chácara no Recanto da Mata, a 3 km de Goianésia, com 5 quartos e 7 banheiros. Muito espaço e conforto.",
    disponivel: true
  },
  {
    id: 48,
    referencia: "CI-048",
    titulo: "Venda – Chácara",
    categoria: "Rural",
    tipo: "Chácara",
    status: "Venda",
    bairro: "",
    localizacao: "",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/048/01.jpeg",
    fotos: ["images/imoveis/048/01.jpeg"],
    data: "",
    descricao: "Chácara em Goianésia com ótima área, perfeita para lazer e descanso.",
    disponivel: true
  },
  {
    id: 49,
    referencia: "CI-049",
    titulo: "Venda – Ágio de Lote",
    categoria: "Terreno",
    tipo: "Lote",
    status: "Venda",
    bairro: "Parque das Palmeiras 3",
    localizacao: "Rua 16A",
    cidade: "Goianésia",
    preco: 45000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/049/01.jpeg",
    fotos: ["images/imoveis/049/01.jpeg"],
    data: "",
    descricao: "Ágio de lote na Rua 16A, Parque das Palmeiras 3. Oportunidade de investimento com excelente preço.",
    disponivel: true
  },
  {
    id: 50,
    referencia: "CI-050",
    titulo: "Venda – 2 Casas",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Jardim do Cerrado",
    localizacao: "",
    cidade: "Goianésia",
    preco: 250000,
    quartos: 4,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/050/01.jpeg",
    fotos: ["images/imoveis/050/01.jpeg"],
    data: "",
    descricao: "Duas casas no Jardim do Cerrado, totalizando 4 quartos e 2 banheiros. Ótima oportunidade de investimento.",
    disponivel: true
  },
  {
    id: 51,
    referencia: "CI-051",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Granville",
    localizacao: "Rua Petrolina, Qd. 91, Lt. 8",
    cidade: "Goianésia",
    preco: 360000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/051/01.jpeg",
    fotos: ["images/imoveis/051/01.jpeg"],
    data: "",
    descricao: "Casa no Granville, na Rua Petrolina, Quadra 91, Lote 8, com 3 quartos e 2 banheiros.",
    disponivel: true
  },
  {
    id: 52,
    referencia: "CI-052",
    titulo: "Venda – lote",
    categoria: "Terreno",
    tipo: "Lote",
    status: "Venda",
    bairro: "",
    localizacao: "Rua Paraguai",
    cidade: "Goianésia",
    preco: 145000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/052/01.jpeg",
    fotos: ["images/imoveis/052/01.jpeg"],
    data: "",
    descricao: "Lote na Rua Paraguai, pronto para construir. Excelente oportunidade.",
    disponivel: true
  },
  {
    id: 53,
    referencia: "CI-053",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "",
    localizacao: "Rua Itapaci, entre as ruas 15 e 17",
    cidade: "Goianésia",
    preco: 650000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/053/01.jpeg",
    fotos: ["images/imoveis/053/01.jpeg"],
    data: "",
    descricao: "Casa na Rua Itapaci, entre as ruas 15 e 17, com 3 quartos e 2 banheiros.",
    disponivel: true
  },
  {
    id: 54,
    referencia: "CI-054",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa em Condomínio",
    status: "Venda",
    bairro: "Condomínio Vivale",
    localizacao: "",
    cidade: "Goianésia",
    preco: 1800000,
    quartos: 3,
    suites: 0,
    banheiros: 3,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/054/01.jpeg",
    fotos: ["images/imoveis/054/01.jpeg"],
    data: "",
    descricao: "Casa no Condomínio Vivale, com 3 quartos e 3 banheiros. Alto padrão e segurança.",
    disponivel: true
  },
  {
    id: 55,
    referencia: "CI-055",
    titulo: "Vendas – Lotes",
    categoria: "Terreno",
    tipo: "Lote",
    status: "Venda",
    bairro: "Condomínio Meridiam",
    localizacao: "",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/055/01.jpeg",
    fotos: ["images/imoveis/055/01.jpeg"],
    data: "",
    descricao: "Lotes no Condomínio Meridiam, perfeito para quem deseja construir em condomínio fechado.",
    disponivel: true
  },
  {
    id: 56,
    referencia: "CI-056",
    titulo: "Venda – Fazenda",
    categoria: "Rural",
    tipo: "Fazenda",
    status: "Venda",
    bairro: "",
    localizacao: "Região de Padre Bernardo - GO",
    cidade: "Padre Bernardo",
    preco: 2500000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/056/01.jpeg",
    fotos: ["images/imoveis/056/01.jpeg"],
    data: "",
    descricao: "Fazenda na região de Padre Bernardo - GO, com grande área. Ótima oportunidade para investimento rural.",
    disponivel: true
  },
  {
    id: 57,
    referencia: "CI-057",
    titulo: "Venda – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Venda",
    bairro: "Centro",
    localizacao: "Av. Goiás (em cima do Crefisa)",
    cidade: "Goianésia",
    preco: 800000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/057/01.jpeg",
    fotos: ["images/imoveis/057/01.jpeg"],
    data: "",
    descricao: "Apartamento na Avenida Goiás, em cima do Crefisa, com 3 quartos e 2 banheiros. Localização central.",
    disponivel: true
  },
  {
    id: 58,
    referencia: "CI-058",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Colina Park",
    localizacao: "",
    cidade: "Goianésia",
    preco: 140000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/058/01.jpeg",
    fotos: ["images/imoveis/058/01.jpeg"],
    data: "",
    descricao: "Casa no Colina Park. Ótima oportunidade para quem busca imóvel em bairro tranquilo.",
    disponivel: true
  },
  {
    id: 59,
    referencia: "CI-059",
    titulo: "Venda – Chácara",
    categoria: "Rural",
    tipo: "Chácara",
    status: "Venda",
    bairro: "",
    localizacao: "Artulândia - GO",
    cidade: "Artulândia",
    preco: 460000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/059/01.jpeg",
    fotos: ["images/imoveis/059/01.jpeg"],
    data: "",
    descricao: "Chácara em Artulândia - Goiás. Ideal para lazer, descanso e contato com a natureza.",
    disponivel: true
  },
  {
    id: 60,
    referencia: "CI-060",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Setor Oeste",
    localizacao: "Av. Contorno, 935A",
    cidade: "Goianésia",
    preco: 350000,
    quartos: 3,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/060/01.jpeg",
    fotos: ["images/imoveis/060/01.jpeg"],
    data: "",
    descricao: "Casa na Av. Contorno, 935A, Setor Oeste, com 3 quartos e 1 banheiro.",
    disponivel: true
  },
  {
    id: 61,
    referencia: "CI-061",
    titulo: "Venda – Lote",
    categoria: "Terreno",
    tipo: "Lote",
    status: "Venda",
    bairro: "",
    localizacao: "Porangatu - GO",
    cidade: "Porangatu",
    preco: 59000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/061/01.jpeg",
    fotos: ["images/imoveis/061/01.jpeg"],
    data: "",
    descricao: "Lote em Porangatu - GO. Ótima oportunidade para construir ou investir.",
    disponivel: true
  },
  {
    id: 62,
    referencia: "CI-062",
    titulo: "Venda – Apartamento",
    categoria: "Residencial",
    tipo: "Apartamento",
    status: "Venda",
    bairro: "Porto Seguro",
    localizacao: "Bloco C, Apt. 103",
    cidade: "Goianésia",
    preco: 260000,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 1,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/062/01.jpeg",
    fotos: ["images/imoveis/062/01.jpeg"],
    data: "",
    descricao: "Apartamento no Condomínio Porto Seguro, Bloco C, com 2 quartos e 1 banheiro.",
    disponivel: true
  },
  {
    id: 63,
    referencia: "CI-063",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "São Cristóvão",
    localizacao: "Rua 23, nº 157A",
    cidade: "Goianésia",
    preco: 680000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/063/01.jpeg",
    fotos: ["images/imoveis/063/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 23, São Cristóvão, com 3 quartos e 2 banheiros. Bem localizada.",
    disponivel: true
  },
  {
    id: 64,
    referencia: "CI-064",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Nova Aurora",
    localizacao: "Av. Contorno, nº 89",
    cidade: "Goianésia",
    preco: 700000,
    quartos: 3,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/064/01.jpeg",
    fotos: ["images/imoveis/064/01.jpeg"],
    data: "",
    descricao: "Casa na Av. Contorno, nº 89, Nova Aurora, com 3 quartos e 1 banheiro.",
    disponivel: true
  },
  {
    id: 65,
    referencia: "CI-065",
    titulo: "Casa a Venda",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "",
    localizacao: "Rua 31, nº 441",
    cidade: "Goianésia",
    preco: 1200000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/065/01.jpg",
    fotos: ["images/imoveis/065/01.jpg"],
    data: "",
    descricao: "Casa na Rua 31, nº 441, com 3 quartos e 2 banheiros. Imóvel de destaque em Goianésia.",
    disponivel: true
  },
  {
    id: 66,
    referencia: "CI-066",
    titulo: "Chacara à Venda – Direção a Barro Alto – GO",
    categoria: "Rural",
    tipo: "Chácara",
    status: "Venda",
    bairro: "",
    localizacao: "Direção a Barro Alto - GO",
    cidade: "Barro Alto",
    preco: 400000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/066/01.jpg",
    fotos: ["images/imoveis/066/01.jpg"],
    data: "",
    descricao: "Chácara à venda na direção a Barro Alto - GO. Ótima oportunidade para quem busca sossego.",
    disponivel: true
  },
  {
    id: 67,
    referencia: "CI-067",
    titulo: "Imóvel a Venda – Granville",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Granville",
    localizacao: "",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/067/01.jpg",
    fotos: ["images/imoveis/067/01.jpg"],
    data: "",
    descricao: "Imóvel no Bairro Granville, com 3 quartos e 2 banheiros. Ótima localização.",
    disponivel: true
  },
  {
    id: 68,
    referencia: "CI-068",
    titulo: "Imóvel a Venda – Colina Park",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Colina Park",
    localizacao: "",
    cidade: "Goianésia",
    preco: 280000,
    quartos: 2,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/068/01.png",
    fotos: ["images/imoveis/068/01.png"],
    data: "",
    descricao: "Imóvel no Bairro Colina Park, com 2 quartos e 1 banheiro. Ótimo custo-benefício.",
    disponivel: true
  },
  {
    id: 69,
    referencia: "CI-069",
    titulo: "Lote a Venda – Condomínio Meridiam",
    categoria: "Terreno",
    tipo: "Lote",
    status: "Venda",
    bairro: "Condomínio Meridiam",
    localizacao: "",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/069/01.png",
    fotos: ["images/imoveis/069/01.png"],
    data: "",
    descricao: "Lote no Condomínio Meridiam, ideal para construir em condomínio fechado.",
    disponivel: true
  },
  {
    id: 70,
    referencia: "CI-070",
    titulo: "Imóvel A Venda – Setor Sul",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Setor Sul",
    localizacao: "Rua 37, nº 556",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 3,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/070/01.jpg",
    fotos: ["images/imoveis/070/01.jpg"],
    data: "",
    descricao: "Imóvel na Rua 37, nº 556, Setor Sul, com 3 quartos e 1 banheiro.",
    disponivel: true
  },
  {
    id: 71,
    referencia: "CI-071",
    titulo: "Imóvel a Venda – Ponto Comercial",
    categoria: "Comercial",
    tipo: "Ponto Comercial",
    status: "Venda",
    bairro: "Centro",
    localizacao: "",
    cidade: "Goianésia",
    preco: 1700000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/071/01.png",
    fotos: ["images/imoveis/071/01.png"],
    data: "",
    descricao: "Ponto comercial no Centro de Goianésia, excelente para o seu negócio.",
    disponivel: true
  },
  {
    id: 72,
    referencia: "CI-072",
    titulo: "Imóvel a Venda – Propriedade Rural",
    categoria: "Rural",
    tipo: "Fazenda",
    status: "Venda",
    bairro: "",
    localizacao: "60 km de Goianésia",
    cidade: "Goianésia",
    preco: 1000000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/072/01.jpg",
    fotos: ["images/imoveis/072/01.jpg"],
    data: "",
    descricao: "Propriedade rural a 60 km de Goianésia. Ótima oportunidade para produção e investimento.",
    disponivel: true
  },
  {
    id: 73,
    referencia: "CI-073",
    titulo: "Imóvel a Venda – Bairro Nova Fiica",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Dona Fiica",
    localizacao: "",
    cidade: "Goianésia",
    preco: 320000,
    quartos: 3,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/073/01.jpeg",
    fotos: ["images/imoveis/073/01.jpeg"],
    data: "",
    descricao: "Imóvel no Bairro Dona Fiica, com 3 quartos e 1 banheiro.",
    disponivel: true
  },
  {
    id: 74,
    referencia: "CI-074",
    titulo: "Imóvel a Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Bouganville",
    localizacao: "",
    cidade: "Goianésia",
    preco: 350000,
    quartos: 3,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/074/01.png",
    fotos: ["images/imoveis/074/01.png"],
    data: "",
    descricao: "Casa no Bairro Bouganville, com 3 quartos e 1 banheiro.",
    disponivel: true
  },
  {
    id: 75,
    referencia: "CI-075",
    titulo: "Imóvel a Venda – Chácara",
    categoria: "Rural",
    tipo: "Chácara",
    status: "Venda",
    bairro: "",
    localizacao: "Sentido Jaraguá",
    cidade: "Goianésia",
    preco: 1000000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/075/01.png",
    fotos: ["images/imoveis/075/01.png"],
    data: "",
    descricao: "Chácara no sentido Jaraguá. Perfeita para lazer e descanso.",
    disponivel: true
  },
  {
    id: 76,
    referencia: "CI-076",
    titulo: "Cobertura com Vista para o Lago Serra da Mesa",
    categoria: "Residencial",
    tipo: "Cobertura",
    status: "Venda",
    bairro: "",
    localizacao: "Uruaçu - GO",
    cidade: "Uruaçu",
    preco: 600000,
    quartos: 3,
    suites: 0,
    banheiros: 3,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/076/01.png",
    fotos: ["images/imoveis/076/01.png"],
    data: "",
    descricao: "Cobertura com vista para o Lago Serra da Mesa, em Uruaçu - GO, com 3 quartos e 3 banheiros.",
    disponivel: true
  },
  {
    id: 77,
    referencia: "CI-077",
    titulo: "Imóvel à Venda – Granville",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Granville",
    localizacao: "",
    cidade: "Goianésia",
    preco: 790000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/077/01.jpg",
    fotos: ["images/imoveis/077/01.jpg"],
    data: "",
    descricao: "Imóvel no Bairro Granville, com 3 quartos e 2 banheiros. Imóvel de alto padrão.",
    disponivel: true
  },
  {
    id: 78,
    referencia: "CI-078",
    titulo: "Casa a Venda",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "",
    localizacao: "Rua 55, esquina com Rua Vasco da Gama",
    cidade: "Goianésia",
    preco: 380000,
    quartos: 3,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/078/01.jpeg",
    fotos: ["images/imoveis/078/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 55, esquina com a Rua Vasco da Gama, com 3 quartos e 1 banheiro.",
    disponivel: true
  },
  {
    id: 79,
    referencia: "CI-079",
    titulo: "Casa a Venda",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Granville",
    localizacao: "Rua Itapaci",
    cidade: "Goianésia",
    preco: 1000000,
    quartos: 3,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/079/01.jpeg",
    fotos: ["images/imoveis/079/01.jpeg"],
    data: "",
    descricao: "Casa na Rua Itapaci, Granville, com 3 quartos e 1 banheiro.",
    disponivel: true
  },
  {
    id: 80,
    referencia: "CI-080",
    titulo: "Um Terreno Á Venda – 03",
    categoria: "Terreno",
    tipo: "Terreno",
    status: "Venda",
    bairro: "",
    localizacao: "GO 080 - Saída para Goiânia",
    cidade: "Goianésia",
    preco: 500000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/080/01.jpeg",
    fotos: ["images/imoveis/080/01.jpeg"],
    data: "",
    descricao: "Terreno na GO 080, saída para Goiânia, do lado do Rancho Paraíso. Excelente oportunidade.",
    disponivel: true
  },
  {
    id: 81,
    referencia: "CI-081",
    titulo: "Casas Á Venda – Condomínio",
    categoria: "Residencial",
    tipo: "Casa em Condomínio",
    status: "Venda",
    bairro: "Reserva da Serra",
    localizacao: "",
    cidade: "Goianésia",
    preco: 255900,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/081/01.jpeg",
    fotos: ["images/imoveis/081/01.jpeg"],
    data: "",
    descricao: "Casas no Condomínio Reserva da Serra, com 3 quartos e 2 banheiros. Segurança e infraestrutura completa.",
    disponivel: true
  },
  {
    id: 82,
    referencia: "CI-082",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Centro",
    localizacao: "Rua 12, nº 281",
    cidade: "Goianésia",
    preco: 500000,
    quartos: 3,
    suites: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/082/01.jpeg",
    fotos: ["images/imoveis/082/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 12, nº 281, Centro, com 3 quartos e 2 banheiros. Localização central.",
    disponivel: true
  },
  {
    id: 83,
    referencia: "CI-083",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Setor Universitário",
    localizacao: "Rua 19, nº 445-A",
    cidade: "Goianésia",
    preco: 1450000,
    quartos: 3,
    suites: 0,
    banheiros: 3,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/083/01.jpeg",
    fotos: ["images/imoveis/083/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 19, Setor Universitário, com 3 quartos e 3 banheiros. Alto padrão.",
    disponivel: true
  },
  {
    id: 84,
    referencia: "CI-084",
    titulo: "Venda – Chácara",
    categoria: "Rural",
    tipo: "Chácara",
    status: "Venda",
    bairro: "",
    localizacao: "",
    cidade: "Goianésia",
    preco: 250000,
    quartos: 3,
    suites: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/084/01.jpeg",
    fotos: ["images/imoveis/084/01.jpeg"],
    data: "",
    descricao: "Chácara em Goianésia, com 3 quartos e 1 banheiro. Ótima oportunidade.",
    disponivel: true
  },
  {
    id: 85,
    referencia: "CI-085",
    titulo: "Venda – Casa",
    categoria: "Residencial",
    tipo: "Casa",
    status: "Venda",
    bairro: "Palmeiras 3",
    localizacao: "Rua 16A",
    cidade: "Goianésia",
    preco: 980000,
    quartos: 3,
    suites: 0,
    banheiros: 3,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/085/01.jpeg",
    fotos: ["images/imoveis/085/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 16A, Palmeiras 3, com 3 quartos e 3 banheiros.",
    disponivel: true
  },
  {
    id: 86,
    referencia: "CI-086",
    titulo: "Venda – Imóvel Comercial",
    categoria: "Comercial",
    tipo: "Prédio",
    status: "Venda",
    bairro: "Carrilho",
    localizacao: "Praça do Carrilho (lado da estação rodoviária)",
    cidade: "Goianésia",
    preco: 2200000,
    quartos: 31,
    suites: 0,
    banheiros: 8,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/086/01.jpeg",
    fotos: ["images/imoveis/086/01.jpeg"],
    data: "",
    descricao: "Imóvel comercial em frente à Praça do Carrilho, do lado da estação rodoviária. Grande estrutura com 31 quartos e 8 banheiros.",
    disponivel: true
  },
  {
    id: 87,
    referencia: "CI-087",
    titulo: "Venda – Loteamento",
    categoria: "Terreno",
    tipo: "Lote",
    status: "Venda",
    bairro: "Granville",
    localizacao: "",
    cidade: "Goianésia",
    preco: 136000,
    quartos: 0,
    suites: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    mobiliado: false,
    destaque: false,
    condominio: null,
    iptu: null,
    imagem: "images/imoveis/087/01.jpeg",
    fotos: ["images/imoveis/087/01.jpeg"],
    data: "",
    descricao: "Loteamento no Residencial Granville. Ótima oportunidade para investimento.",
    disponivel: true
  }
];

window.CONTATOS = {
  telefoneAluguel: "(62) 98507-0819",
  telefoneVendas: "(62) 98415-8065",
  telefoneVendas2: "(62) 98415-8065",
  whatsapp: "5562985070819",
  email: "contato@caetanoimoveis.com.br",
  endereco: "R. 29, 365 Centro - Goianésia - GO",
  horario: "07:30 - 17:00 (Seg-Sex)",
  instagram: "https://www.instagram.com/caetanoimoveisgoianesia/",
  facebook: "https://www.facebook.com/caetanoimoveisgoianesia",
  whatsappApi: "https://api.whatsapp.com/send/?phone=5562985070819&text&type=phone_number&app_absent=0"
};
