const IMOVEIS = [
  {
    id: 1,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Residencial Mariana, Apt. 401 bloco 04",
    cidade: "Goianésia",
    preco: 1300,
    quartos: 2,
    banheiros: 1,
    garagem: 1,
    area: 55,
    imagem: "images/imoveis/001/01.jpeg",
    fotos: ["images/imoveis/001/01.jpeg"],
    data: "2026-08-01",
    descricao: "Apartamento localizado no Residencial Mariana, com 2 quartos e 1 banheiro. Ambiente confortável e bem localizado para moradia."
  },
  {
    id: 2,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Residencial Mariana, Apt. 204 bloco 11",
    cidade: "Goianésia",
    preco: 1300,
    quartos: 2,
    banheiros: 1,
    garagem: 1,
    area: 55,
    imagem: "images/imoveis/002/01.jpeg",
    fotos: ["images/imoveis/002/01.jpeg"],
    data: "2026-07-10",
    descricao: "Apartamento no Residencial Mariana, 2 quartos e 1 banheiro, ideal para famílias que buscam conforto e segurança."
  },
  {
    id: 3,
    titulo: "Aluguel – Casa",
    tipo: "Casa",
    status: "Aluguel",
    localizacao: "Rua 14, n° 444 St. universitário",
    cidade: "Goianésia",
    preco: 2300,
    quartos: 3,
    banheiros: 3,
    garagem: 2,
    area: 180,
    imagem: "images/imoveis/003/01.jpeg",
    fotos: ["images/imoveis/003/01.jpeg"],
    data: "2026-07-16",
    descricao: "Casa espaçosa com 3 quartos e 3 banheiros no Setor Universitário. Ótima localização e área ampla."
  },
  {
    id: 4,
    titulo: "Aluguel – Casa",
    tipo: "Casa",
    status: "Aluguel",
    localizacao: "Rua Zico Fraga, Qd. 40 Lt. 09 Residencial Ipê",
    cidade: "Goianésia",
    preco: 1100,
    quartos: 2,
    banheiros: 1,
    garagem: 1,
    area: 100,
    imagem: "images/imoveis/004/01.jpeg",
    fotos: ["images/imoveis/004/01.jpeg"],
    data: "2026-07-17",
    descricao: "Casa aconchegante no Residencial Ipê, com 2 quartos e 1 banheiro. Ótima opção para quem busca tranquilidade."
  },
  {
    id: 5,
    titulo: "Aluguel – Casa",
    tipo: "Casa",
    status: "Aluguel",
    localizacao: "Rua 37, n° 540 Setor Sul",
    cidade: "Goianésia",
    preco: 2700,
    quartos: 4,
    banheiros: 3,
    garagem: 2,
    area: 220,
    imagem: "images/imoveis/005/01.jpeg",
    fotos: ["images/imoveis/005/01.jpeg"],
    data: "2026-07-21",
    descricao: "Casa ampla no Setor Sul com 4 quartos e 3 banheiros. Perfeita para famílias que necessitam de espaço e conforto."
  },
  {
    id: 6,
    titulo: "Aluguel – Galpão",
    tipo: "Galpão",
    status: "Aluguel",
    localizacao: "Av. Alameda Otávio Lage, palmeiras 01",
    cidade: "Goianésia",
    preco: 4500,
    quartos: 0,
    banheiros: 3,
    garagem: 0,
    area: 500,
    imagem: "images/imoveis/006/01.jpeg",
    fotos: ["images/imoveis/006/01.jpeg"],
    data: "2026-07-18",
    descricao: "Galpão comercial na Avenida Alameda Otávio Lage, com grande área útil, ideal para indústria, comércio ou estoque."
  },
  {
    id: 7,
    titulo: "Aluguel – Casa",
    tipo: "Casa",
    status: "Aluguel",
    localizacao: "Rua Dona Cida, Qd.12 Lt. 09 A Nestor Ville",
    cidade: "Goianésia",
    preco: 1400,
    quartos: 2,
    banheiros: 2,
    garagem: 1,
    area: 120,
    imagem: "images/imoveis/007/01.jpeg",
    fotos: ["images/imoveis/007/01.jpeg"],
    data: "2026-07-29",
    descricao: "Casa no Nestor Ville com 2 quartos e 2 banheiros. Bairro calmo e familiar, ideal para moradia."
  },
  {
    id: 8,
    titulo: "Aluguel – Galpão",
    tipo: "Galpão",
    status: "Aluguel",
    localizacao: "Av. Laurentino Martins, n° 2.575 Qd. 28 Lt. 14",
    cidade: "Goianésia",
    preco: 4052.5,
    quartos: 0,
    banheiros: 2,
    garagem: 0,
    area: 450,
    imagem: "images/imoveis/008/01.jpeg",
    fotos: ["images/imoveis/008/01.jpeg"],
    data: "2026-07-30",
    descricao: "Galpão na Avenida Laurentino Martins, excelente localização e ótimo espaço para atividades comerciais ou industriais."
  },
  {
    id: 9,
    titulo: "Aluguel – Kit net",
    tipo: "Kitnet",
    status: "Aluguel",
    localizacao: "Rua 29, n° 365 Centro entre a Av. Brasil e Av. Mato Grosso",
    cidade: "Goianésia",
    preco: 700,
    quartos: 1,
    banheiros: 1,
    garagem: 0,
    area: 35,
    imagem: "images/imoveis/009/01.jpeg",
    fotos: ["images/imoveis/009/01.jpeg"],
    data: "2026-07-30",
    descricao: "Kitnet no Centro de Goianésia, em frente ao escritório da Caetano Imóveis. Prática, mobiliada e perto de tudo."
  },
  {
    id: 10,
    titulo: "Aluguel – Kit net",
    tipo: "Kitnet",
    status: "Aluguel",
    localizacao: "Rua Meriti, Qd. 08 Lt. 22 Palmeiras 3",
    cidade: "Goianésia",
    preco: 800,
    quartos: 1,
    banheiros: 1,
    garagem: 0,
    area: 38,
    imagem: "images/imoveis/010/01.jpeg",
    fotos: ["images/imoveis/010/01.jpeg"],
    data: "2026-07-31",
    descricao: "Kitnet no Bairro Palmeiras 3, 1 quarto e 1 banheiro. Ótimo custo-benefício para quem busca praticidade."
  },
  {
    id: 11,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Rua 21, 441 Setor Universitário",
    cidade: "Goianésia",
    preco: 2500,
    quartos: 2,
    banheiros: 2,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/011/01.jpeg",
    fotos: ["images/imoveis/011/01.jpeg"],
    data: "",
    descricao: "Apartamento no Setor Universitário com 2 quartos e 2 banheiros, em ótima localização e pronto para morar."
  },
  {
    id: 12,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Residencial Mariana, Apt. 103 bloco 07",
    cidade: "Goianésia",
    preco: 800,
    quartos: 2,
    banheiros: 1,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/012/01.jpeg",
    fotos: ["images/imoveis/012/01.jpeg"],
    data: "",
    descricao: "Apartamento no Residencial Mariana, 2 quartos e 1 banheiro, ótima oportunidade com excelente custo-benefício."
  },
  {
    id: 13,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Residencial Mariana, Apt. 401 bloco 13",
    cidade: "Goianésia",
    preco: 1350,
    quartos: 2,
    banheiros: 1,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/013/01.jpeg",
    fotos: ["images/imoveis/013/01.jpeg"],
    data: "",
    descricao: "Apartamento no Residencial Mariana com 2 quartos e 1 banheiro. Conforto e praticidade para você e sua família."
  },
  {
    id: 14,
    titulo: "Aluguel – Casa",
    tipo: "Casa",
    status: "Aluguel",
    localizacao: "Rua 08, n° 305 Setor sul",
    cidade: "Goianésia",
    preco: 1800,
    quartos: 3,
    banheiros: 2,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/014/01.jpeg",
    fotos: ["images/imoveis/014/01.jpeg"],
    data: "",
    descricao: "Casa no Setor Sul com 3 quartos e 2 banheiros. Espaço ideal para quem busca conforto e boa localização."
  },
  {
    id: 15,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Rua 29, n° 412 apt. 02 Centro",
    cidade: "Goianésia",
    preco: 1700,
    quartos: 2,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/015/01.jpeg",
    fotos: ["images/imoveis/015/01.jpeg"],
    data: "",
    descricao: "Apartamento no Centro de Goianésia com 2 quartos e 1 banheiro, perto de comércio e serviços."
  },
  {
    id: 16,
    titulo: "Aluguel – Ponto/Casa",
    tipo: "Ponto/Casa",
    status: "Aluguel",
    localizacao: "Rua 29, n° 374 Centro",
    cidade: "Goianésia",
    preco: 1800,
    quartos: 2,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/016/01.jpeg",
    fotos: ["images/imoveis/016/01.jpeg"],
    data: "",
    descricao: "Ponto comercial com casa no Centro de Goianésia, ideal para quem deseja morar e trabalhar no mesmo local."
  },
  {
    id: 17,
    titulo: "Aluguel – Casa",
    tipo: "Casa",
    status: "Aluguel",
    localizacao: "Av. contorno, n° 89 Nova Aurora",
    cidade: "Goianésia",
    preco: 2000,
    quartos: 3,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/017/01.jpeg",
    fotos: ["images/imoveis/017/01.jpeg"],
    data: "",
    descricao: "Casa no Bairro Nova Aurora com 3 quartos e 1 banheiro. Ótima opção para locação em localização privilegiada."
  },
  {
    id: 18,
    titulo: "Aluguel – Kitnet",
    tipo: "Kitnet",
    status: "Aluguel",
    localizacao: "Rua Jaraguá, n° 31 Qd. 17 Lt. 08 Residencial Granville",
    cidade: "Goianésia",
    preco: 880,
    quartos: 2,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/018/01.jpeg",
    fotos: ["images/imoveis/018/01.jpeg"],
    data: "",
    descricao: "Kitnet no Residencial Granville com 2 quartos e 1 banheiro. Prática, moderna e em ótimo bairro."
  },
  {
    id: 19,
    titulo: "Aluguel – Kitnet",
    tipo: "Kitnet",
    status: "Aluguel",
    localizacao: "Rua 25, n° 262 kitnet 06 - Carrilho",
    cidade: "Goianésia",
    preco: 800,
    quartos: 1,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/019/01.jpeg",
    fotos: ["images/imoveis/019/01.jpeg"],
    data: "",
    descricao: "Kitnet no Bairro Carrilho com 1 quarto e 1 banheiro, perfeita para quem busca praticidade e economia."
  },
  {
    id: 20,
    titulo: "Aluguel – Casa",
    tipo: "Casa",
    status: "Aluguel",
    localizacao: "Rua Pinheiro, n° 227 entre a 32 e 34 - Aldeia do Morro",
    cidade: "Goianésia",
    preco: 1000,
    quartos: 2,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/020/01.jpeg",
    fotos: ["images/imoveis/020/01.jpeg"],
    data: "",
    descricao: "Casa na Aldeia do Morro com 2 quartos e 2 banheiros, em bairro tranquilo e bem localizado."
  },
  {
    id: 21,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Av. goiás, nº 1231 - Setor sul",
    cidade: "Goianésia",
    preco: 1700,
    quartos: 1,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/021/01.jpeg",
    fotos: ["images/imoveis/021/01.jpeg"],
    data: "",
    descricao: "Apartamento na Avenida Goiás, Setor Sul, com 1 quarto e 2 banheiros. Excelente localização."
  },
  {
    id: 22,
    titulo: "Aluguel – Espaço",
    tipo: "Espaço",
    status: "Aluguel",
    localizacao: "Barro Alto-GO",
    cidade: "Barro Alto",
    preco: 2824,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/022/01.jpg",
    fotos: ["images/imoveis/022/01.jpg"],
    data: "",
    descricao: "Espaço para locação em Barro Alto - GO, ideal para eventos, comércio ou outras atividades."
  },
  {
    id: 23,
    titulo: "Aluguel – Espaço",
    tipo: "Espaço",
    status: "Aluguel",
    localizacao: "Barro Alto-GO",
    cidade: "Barro Alto",
    preco: 4500,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/023/01.jpg",
    fotos: ["images/imoveis/023/01.jpg"],
    data: "",
    descricao: "Espaço amplo para locação em Barro Alto - GO, com ótima estrutura para diversos usos."
  },
  {
    id: 24,
    titulo: "Aluguel – Área",
    tipo: "Área",
    status: "Aluguel",
    localizacao: "Rua 22 Entre as ruas 45 a 49 - Muniz falcão",
    cidade: "Goianésia",
    preco: 6072,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/024/01.jpeg",
    fotos: ["images/imoveis/024/01.jpeg"],
    data: "",
    descricao: "Área para locação na Rua 22, entre as ruas 45 a 49, Muniz Falcão. Perfeita para atividades comerciais."
  },
  {
    id: 25,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Avenida Goiás número 1.231 - Centro",
    cidade: "Goianésia",
    preco: 1800,
    quartos: 1,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/025/01.jpeg",
    fotos: ["images/imoveis/025/01.jpeg"],
    data: "",
    descricao: "Apartamento na Avenida Goiás, Centro, com 1 quarto e 1 banheiro. Localização central e prática."
  },
  {
    id: 26,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Apartamento na rua 31 setor sul nº 487",
    cidade: "Goianésia",
    preco: 1650,
    quartos: 2,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/026/01.jpeg",
    fotos: ["images/imoveis/026/01.jpeg"],
    data: "",
    descricao: "Apartamento na Rua 31, Setor Sul, nº 487, com 2 quartos e 1 banheiro. Ótima localização."
  },
  {
    id: 27,
    titulo: "Aluguel – Galpão",
    tipo: "Galpão",
    status: "Aluguel",
    localizacao: "Rua 34 Galpão",
    cidade: "Goianésia",
    preco: 2800,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/027/01.jpeg",
    fotos: ["images/imoveis/027/01.jpeg"],
    data: "",
    descricao: "Galpão na Rua 34, ideal para comércio, indústria ou estoque em Goianésia."
  },
  {
    id: 28,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Rua Jequitiba, Qd. 31, Lt. 8/9, Palmeiras 2 - Residencial LOPES",
    cidade: "Goianésia",
    preco: 1500,
    quartos: 2,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/028/01.jpeg",
    fotos: ["images/imoveis/028/01.jpeg"],
    data: "",
    descricao: "Apartamento no Residencial Lopes, Palmeiras 2, com 2 quartos e 1 banheiro, em área tranquila."
  },
  {
    id: 29,
    titulo: "Aluguel – Comercial",
    tipo: "Comercial",
    status: "Aluguel",
    localizacao: "Rua 29, 402, entre 12 e 14 - centro",
    cidade: "Goianésia",
    preco: 4000,
    quartos: 0,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/029/01.jpeg",
    fotos: ["images/imoveis/029/01.jpeg"],
    data: "",
    descricao: "Imóvel comercial no Centro de Goianésia, na Rua 29, com excelente ponto para o seu negócio."
  },
  {
    id: 30,
    titulo: "Aluguel – Comercial",
    tipo: "Comercial",
    status: "Aluguel",
    localizacao: "Rua 33 - centro",
    cidade: "Goianésia",
    preco: 3242,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/030/01.jpeg",
    fotos: ["images/imoveis/030/01.jpeg"],
    data: "",
    descricao: "Imóvel comercial na Rua 33, Centro de Goianésia. Ótima oportunidade para comércio."
  },
  {
    id: 31,
    titulo: "Galpão para Oficina no Gaiola",
    tipo: "Galpão",
    status: "Aluguel",
    localizacao: "Souzalândia-GO",
    cidade: "Souzalândia",
    preco: 1400,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/031/01.jpg",
    fotos: ["images/imoveis/031/01.jpg"],
    data: "",
    descricao: "Galpão para oficina no Gaiola, Souzalândia - GO. Ideal para mecânicas e serviços."
  },
  {
    id: 32,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Av. Laurentino Martins - condomínio Porto Seguro - Bloco D Apt. 202",
    cidade: "Goianésia",
    preco: 1600,
    quartos: 2,
    banheiros: 1,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/032/01.jpeg",
    fotos: ["images/imoveis/032/01.jpeg"],
    data: "",
    descricao: "Apartamento no Condomínio Porto Seguro, Bloco D, com 2 quartos e 1 banheiro. Segurança e conforto."
  },
  {
    id: 33,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "condomínio Porto seguro ap 304 blocoA",
    cidade: "Goianésia",
    preco: 1900,
    quartos: 2,
    banheiros: 1,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/033/01.jpeg",
    fotos: ["images/imoveis/033/01.jpeg"],
    data: "",
    descricao: "Apartamento no Condomínio Porto Seguro, Bloco A, com 2 quartos e 1 banheiro. Estrutura completa."
  },
  {
    id: 34,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "condomínio Boulevard, Ap. 404 bloco B",
    cidade: "Goianésia",
    preco: 1621,
    quartos: 2,
    banheiros: 1,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/034/01.jpeg",
    fotos: ["images/imoveis/034/01.jpeg"],
    data: "",
    descricao: "Apartamento no Condomínio Boulevard, Bloco B, com 2 quartos e 1 banheiro. Moderno e bem localizado."
  },
  {
    id: 35,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "av goias, n 1231, ap 02 setor sul",
    cidade: "Goianésia",
    preco: 1800,
    quartos: 1,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/035/01.jpeg",
    fotos: ["images/imoveis/035/01.jpeg"],
    data: "",
    descricao: "Apartamento na Avenida Goiás, Setor Sul, com 1 quarto e 2 banheiros. Localização central."
  },
  {
    id: 36,
    titulo: "Aluguel – Galpão",
    tipo: "Galpão",
    status: "Aluguel",
    localizacao: "Rua 29 n 195 Carrilho entre a 34 e 36",
    cidade: "Goianésia",
    preco: 1500,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/036/01.jpeg",
    fotos: ["images/imoveis/036/01.jpeg"],
    data: "",
    descricao: "Galpão na Rua 29, Bairro Carrilho, entre as ruas 34 e 36. Bom espaço para diversos usos."
  },
  {
    id: 37,
    titulo: "Aluguel – Casa",
    tipo: "Casa",
    status: "Aluguel",
    localizacao: "rua jussara n 17 parque das palmeiras 3",
    cidade: "Goianésia",
    preco: 1621,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/037/01.jpeg",
    fotos: ["images/imoveis/037/01.jpeg"],
    data: "",
    descricao: "Casa no Parque das Palmeiras 3, com 3 quartos e 2 banheiros. Ótima opção para famílias."
  },
  {
    id: 38,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Rua 12, entre Av. Goiás e a 29",
    cidade: "Goianésia",
    preco: 2200,
    quartos: 3,
    banheiros: 2,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/038/01.jpeg",
    fotos: ["images/imoveis/038/01.jpeg"],
    data: "",
    descricao: "Apartamento na Rua 12, entre Av. Goiás e Rua 29, com 3 quartos e 2 banheiros. Amplo e bem localizado."
  },
  {
    id: 39,
    titulo: "Aluguel – Galpão",
    tipo: "Galpão",
    status: "Aluguel",
    localizacao: "Av. Brasil, Palmeiras 2",
    cidade: "Goianésia",
    preco: 5500,
    quartos: 0,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/039/01.jpeg",
    fotos: ["images/imoveis/039/01.jpeg"],
    data: "",
    descricao: "Galpão na Avenida Brasil, Palmeiras 2, com grande área. Ideal para indústria ou comércio."
  },
  {
    id: 40,
    titulo: "Aluguel – Apartamento",
    tipo: "Apartamento",
    status: "Aluguel",
    localizacao: "Rua 10 esq. Av. Mato Grosso",
    cidade: "Goianésia",
    preco: 2500,
    quartos: 3,
    banheiros: 2,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/040/01.jpeg",
    fotos: ["images/imoveis/040/01.jpeg"],
    data: "",
    descricao: "Apartamento na Rua 10, esquina com Av. Mato Grosso, com 3 quartos e 2 banheiros. Localização central."
  },
  {
    id: 41,
    titulo: "Venda – Chácara",
    tipo: "Chácara",
    status: "Venda",
    localizacao: "26 km de goianesia - Souzalandia",
    cidade: "Souzalândia",
    preco: 1000000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/041/01.jpeg",
    fotos: ["images/imoveis/041/01.jpeg"],
    data: "",
    descricao: "Chácara a 26 km de Goianésia, em Souzalândia, com 3 quartos e 2 banheiros. Ótimo para descanso e lazer."
  },
  {
    id: 42,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Palmeiras 2",
    cidade: "Goianésia",
    preco: 370000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/042/01.jpeg",
    fotos: ["images/imoveis/042/01.jpeg"],
    data: "",
    descricao: "Casa no Bairro Palmeiras 2, com 3 quartos e 2 banheiros. Ótima oportunidade para investir."
  },
  {
    id: 43,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua 35, Nº 259 - Bairro Carrilho",
    cidade: "Goianésia",
    preco: 500000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/043/01.jpeg",
    fotos: ["images/imoveis/043/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 35, Bairro Carrilho, com 3 quartos e 2 banheiros. Bem localizada."
  },
  {
    id: 44,
    titulo: "Venda – 2 Lotes",
    tipo: "Lote",
    status: "Venda",
    localizacao: "Avenida Principal com a rua 07 - Setor Granville",
    cidade: "Goianésia",
    preco: 275000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/044/01.jpeg",
    fotos: ["images/imoveis/044/01.jpeg"],
    data: "",
    descricao: "2 lotes no Setor Granville, na Avenida Principal com a Rua 07. Excelente localização para construir."
  },
  {
    id: 45,
    titulo: "Casa – Venda",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua enomia Machado, número 11 - Cirilandia",
    cidade: "Cirilândia",
    preco: 600000,
    quartos: 4,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/045/01.jpeg",
    fotos: ["images/imoveis/045/01.jpeg"],
    data: "",
    descricao: "Casa em Cirilândia, na Rua Enomia Machado, nº 11, com 4 quartos e 2 banheiros. Amplo imóvel."
  },
  {
    id: 46,
    titulo: "Venda – Lotes",
    tipo: "Lote",
    status: "Venda",
    localizacao: "RUA BACURI, QD 25 LT 05 a 07 - Palmeiras",
    cidade: "Goianésia",
    preco: 190000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/046/01.jpeg",
    fotos: ["images/imoveis/046/01.jpeg"],
    data: "",
    descricao: "Lotes na Rua Bacuri, Quadra 25, Lotes 05 a 07, no Bairro Palmeiras. Ótimo para investimento."
  },
  {
    id: 47,
    titulo: "Venda – Chácara",
    tipo: "Chácara",
    status: "Venda",
    localizacao: "Recanto da mata, 3km de Goianésia",
    cidade: "Goianésia",
    preco: 1000000,
    quartos: 5,
    banheiros: 7,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/047/01.jpeg",
    fotos: ["images/imoveis/047/01.jpeg"],
    data: "",
    descricao: "Chácara no Recanto da Mata, a 3 km de Goianésia, com 5 quartos e 7 banheiros. Muito espaço e conforto."
  },
  {
    id: 48,
    titulo: "Venda – Chácara",
    tipo: "Chácara",
    status: "Venda",
    localizacao: "Goianésia",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/048/01.jpeg",
    fotos: ["images/imoveis/048/01.jpeg"],
    data: "",
    descricao: "Chácara em Goianésia com ótima área, perfeita para lazer e descanso."
  },
  {
    id: 49,
    titulo: "Venda – Ágio de Lote",
    tipo: "Lote",
    status: "Venda",
    localizacao: "Rua 16a - Pq. das palmeiras 3",
    cidade: "Goianésia",
    preco: 45000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/049/01.jpeg",
    fotos: ["images/imoveis/049/01.jpeg"],
    data: "",
    descricao: "Ágio de lote na Rua 16A, Parque das Palmeiras 3. Oportunidade de investimento com excelente preço."
  },
  {
    id: 50,
    titulo: "Venda – 2 Casas",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Jardim do Cerrado",
    cidade: "Goianésia",
    preco: 250000,
    quartos: 4,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/050/01.jpeg",
    fotos: ["images/imoveis/050/01.jpeg"],
    data: "",
    descricao: "Duas casas no Jardim do Cerrado, totalizando 4 quartos e 2 banheiros. Ótima oportunidade de investimento."
  },
  {
    id: 51,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua Petrolina Qd 91 Lt 8 Entre ruas 3 e 5 - Granville",
    cidade: "Goianésia",
    preco: 360000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/051/01.jpeg",
    fotos: ["images/imoveis/051/01.jpeg"],
    data: "",
    descricao: "Casa no Granville, na Rua Petrolina, Quadra 91, Lote 8, com 3 quartos e 2 banheiros."
  },
  {
    id: 52,
    titulo: "Venda – lote",
    tipo: "Lote",
    status: "Venda",
    localizacao: "Rua Paraguai",
    cidade: "Goianésia",
    preco: 145000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/052/01.jpeg",
    fotos: ["images/imoveis/052/01.jpeg"],
    data: "",
    descricao: "Lote na Rua Paraguai, pronto para construir. Excelente oportunidade."
  },
  {
    id: 53,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua Itapaci - Entre as ruas 15/17",
    cidade: "Goianésia",
    preco: 650000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/053/01.jpeg",
    fotos: ["images/imoveis/053/01.jpeg"],
    data: "",
    descricao: "Casa na Rua Itapaci, entre as ruas 15 e 17, com 3 quartos e 2 banheiros."
  },
  {
    id: 54,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Condomínio Vivale",
    cidade: "Goianésia",
    preco: 1800000,
    quartos: 3,
    banheiros: 3,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/054/01.jpeg",
    fotos: ["images/imoveis/054/01.jpeg"],
    data: "",
    descricao: "Casa no Condomínio Vivale, com 3 quartos e 3 banheiros. Alto padrão e segurança."
  },
  {
    id: 55,
    titulo: "Vendas – Lotes",
    tipo: "Lote",
    status: "Venda",
    localizacao: "Condomínio Meridiam",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/055/01.jpeg",
    fotos: ["images/imoveis/055/01.jpeg"],
    data: "",
    descricao: "Lotes no Condomínio Meridiam, perfeito para quem deseja construir em condomínio fechado."
  },
  {
    id: 56,
    titulo: "Venda – Fazenda",
    tipo: "Fazenda",
    status: "Venda",
    localizacao: "Região de Padre Bernardo/GO",
    cidade: "Padre Bernardo",
    preco: 2500000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/056/01.jpeg",
    fotos: ["images/imoveis/056/01.jpeg"],
    data: "",
    descricao: "Fazenda na região de Padre Bernardo - GO, com grande área. Ótima oportunidade para investimento rural."
  },
  {
    id: 57,
    titulo: "Venda – Apartamento",
    tipo: "Apartamento",
    status: "Venda",
    localizacao: "Av Goiás em cima do crefisa",
    cidade: "Goianésia",
    preco: 800000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/057/01.jpeg",
    fotos: ["images/imoveis/057/01.jpeg"],
    data: "",
    descricao: "Apartamento na Avenida Goiás, em cima do Crefisa, com 3 quartos e 2 banheiros. Localização central."
  },
  {
    id: 58,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Colina Park",
    cidade: "Goianésia",
    preco: 140000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/058/01.jpeg",
    fotos: ["images/imoveis/058/01.jpeg"],
    data: "",
    descricao: "Casa no Colina Park. Ótima oportunidade para quem busca imóvel em bairro tranquilo."
  },
  {
    id: 59,
    titulo: "Venda – Chácara",
    tipo: "Chácara",
    status: "Venda",
    localizacao: "Chácara em Artulândia - Goiás",
    cidade: "Artulândia",
    preco: 460000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/059/01.jpeg",
    fotos: ["images/imoveis/059/01.jpeg"],
    data: "",
    descricao: "Chácara em Artulândia - Goiás. Ideal para lazer, descanso e contato com a natureza."
  },
  {
    id: 60,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Av. contorno, 935a - Setor Oeste",
    cidade: "Goianésia",
    preco: 350000,
    quartos: 3,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/060/01.jpeg",
    fotos: ["images/imoveis/060/01.jpeg"],
    data: "",
    descricao: "Casa na Av. Contorno, 935A, Setor Oeste, com 3 quartos e 1 banheiro."
  },
  {
    id: 61,
    titulo: "Venda – Lote",
    tipo: "Lote",
    status: "Venda",
    localizacao: "Porangatu - Go",
    cidade: "Porangatu",
    preco: 59000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/061/01.jpeg",
    fotos: ["images/imoveis/061/01.jpeg"],
    data: "",
    descricao: "Lote em Porangatu - GO. Ótima oportunidade para construir ou investir."
  },
  {
    id: 62,
    titulo: "Venda – Apartamento",
    tipo: "Apartamento",
    status: "Venda",
    localizacao: "Condomínio Porto Seguro, bloco C Apt. 103",
    cidade: "Goianésia",
    preco: 260000,
    quartos: 2,
    banheiros: 1,
    garagem: 1,
    area: 0,
    imagem: "images/imoveis/062/01.jpeg",
    fotos: ["images/imoveis/062/01.jpeg"],
    data: "",
    descricao: "Apartamento no Condomínio Porto Seguro, Bloco C, com 2 quartos e 1 banheiro."
  },
  {
    id: 63,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua 23, n° 157 A São Cristóvão",
    cidade: "Goianésia",
    preco: 680000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/063/01.jpeg",
    fotos: ["images/imoveis/063/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 23, São Cristóvão, com 3 quartos e 2 banheiros. Bem localizada."
  },
  {
    id: 64,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Av. contorno, n° 89 Nova Aurora",
    cidade: "Goianésia",
    preco: 700000,
    quartos: 3,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/064/01.jpeg",
    fotos: ["images/imoveis/064/01.jpeg"],
    data: "",
    descricao: "Casa na Av. Contorno, nº 89, Nova Aurora, com 3 quartos e 1 banheiro."
  },
  {
    id: 65,
    titulo: "Casa a Venda",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua 31 Nº 441",
    cidade: "Goianésia",
    preco: 1200000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/065/01.jpg",
    fotos: ["images/imoveis/065/01.jpg"],
    data: "",
    descricao: "Casa na Rua 31, nº 441, com 3 quartos e 2 banheiros. Imóvel de destaque em Goianésia."
  },
  {
    id: 66,
    titulo: "Chacara à Venda – Direção a Barro Alto – GO",
    tipo: "Chácara",
    status: "Venda",
    localizacao: "Direção a Barro Alto-GO",
    cidade: "Barro Alto",
    preco: 400000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/066/01.jpg",
    fotos: ["images/imoveis/066/01.jpg"],
    data: "",
    descricao: "Chácara à venda na direção a Barro Alto - GO. Ótima oportunidade para quem busca sossego."
  },
  {
    id: 67,
    titulo: "Imóvel a Venda – Granville",
    tipo: "Imóvel",
    status: "Venda",
    localizacao: "Bairro Granville",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/067/01.jpg",
    fotos: ["images/imoveis/067/01.jpg"],
    data: "",
    descricao: "Imóvel no Bairro Granville, com 3 quartos e 2 banheiros. Ótima localização."
  },
  {
    id: 68,
    titulo: "Imóvel a Venda – Colina Park",
    tipo: "Imóvel",
    status: "Venda",
    localizacao: "Bairro: Colina Park",
    cidade: "Goianésia",
    preco: 280000,
    quartos: 2,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/068/01.png",
    fotos: ["images/imoveis/068/01.png"],
    data: "",
    descricao: "Imóvel no Bairro Colina Park, com 2 quartos e 1 banheiro. Ótimo custo-benefício."
  },
  {
    id: 69,
    titulo: "Lote a Venda – Condomínio Meridiam",
    tipo: "Lote",
    status: "Venda",
    localizacao: "Condomínio Meridiam",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/069/01.png",
    fotos: ["images/imoveis/069/01.png"],
    data: "",
    descricao: "Lote no Condomínio Meridiam, ideal para construir em condomínio fechado."
  },
  {
    id: 70,
    titulo: "Imóvel A Venda – Setor Sul",
    tipo: "Imóvel",
    status: "Venda",
    localizacao: "Rua 37, Nº 556 - Setor Sul",
    cidade: "Goianésia",
    preco: 400000,
    quartos: 3,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/070/01.jpg",
    fotos: ["images/imoveis/070/01.jpg"],
    data: "",
    descricao: "Imóvel na Rua 37, nº 556, Setor Sul, com 3 quartos e 1 banheiro."
  },
  {
    id: 71,
    titulo: "Imóvel a Venda – Ponto Comercial",
    tipo: "Comercial",
    status: "Venda",
    localizacao: "Centro",
    cidade: "Goianésia",
    preco: 1700000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/071/01.png",
    fotos: ["images/imoveis/071/01.png"],
    data: "",
    descricao: "Ponto comercial no Centro de Goianésia, excelente para o seu negócio."
  },
  {
    id: 72,
    titulo: "Imóvel a Venda – Propriedade Rural",
    tipo: "Fazenda",
    status: "Venda",
    localizacao: "60 Km de Goianésia",
    cidade: "Goianésia",
    preco: 1000000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/072/01.jpg",
    fotos: ["images/imoveis/072/01.jpg"],
    data: "",
    descricao: "Propriedade rural a 60 km de Goianésia. Ótima oportunidade para produção e investimento."
  },
  {
    id: 73,
    titulo: "Imóvel a Venda – Bairro Nova Fiica",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Bairro Dona Fiica",
    cidade: "Goianésia",
    preco: 320000,
    quartos: 3,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/073/01.jpeg",
    fotos: ["images/imoveis/073/01.jpeg"],
    data: "",
    descricao: "Imóvel no Bairro Dona Fiica, com 3 quartos e 1 banheiro."
  },
  {
    id: 74,
    titulo: "Imóvel a Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Bairro Bouganville",
    cidade: "Goianésia",
    preco: 350000,
    quartos: 3,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/074/01.png",
    fotos: ["images/imoveis/074/01.png"],
    data: "",
    descricao: "Casa no Bairro Bouganville, com 3 quartos e 1 banheiro."
  },
  {
    id: 75,
    titulo: "Imóvel a Venda – Chácara",
    tipo: "Chácara",
    status: "Venda",
    localizacao: "Sentido Jaraguá",
    cidade: "Goianésia",
    preco: 1000000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/075/01.png",
    fotos: ["images/imoveis/075/01.png"],
    data: "",
    descricao: "Chácara no sentido Jaraguá. Perfeita para lazer e descanso."
  },
  {
    id: 76,
    titulo: "Cobertura com Vista para o Lago Serra da Mesa",
    tipo: "Cobertura",
    status: "Venda",
    localizacao: "Uruaçu-GO",
    cidade: "Uruaçu",
    preco: 600000,
    quartos: 3,
    banheiros: 3,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/076/01.png",
    fotos: ["images/imoveis/076/01.png"],
    data: "",
    descricao: "Cobertura com vista para o Lago Serra da Mesa, em Uruaçu - GO, com 3 quartos e 3 banheiros."
  },
  {
    id: 77,
    titulo: "Imóvel à Venda – Granville",
    tipo: "Imóvel",
    status: "Venda",
    localizacao: "Bairro Granville",
    cidade: "Goianésia",
    preco: 790000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/077/01.jpg",
    fotos: ["images/imoveis/077/01.jpg"],
    data: "",
    descricao: "Imóvel no Bairro Granville, com 3 quartos e 2 banheiros. Imóvel de alto padrão."
  },
  {
    id: 78,
    titulo: "Casa a Venda",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua 55 - Esq com a Rua Vasco da Gama",
    cidade: "Goianésia",
    preco: 380000,
    quartos: 3,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/078/01.jpeg",
    fotos: ["images/imoveis/078/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 55, esquina com a Rua Vasco da Gama, com 3 quartos e 1 banheiro."
  },
  {
    id: 79,
    titulo: "Casa a Venda",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua Itapaci - Granville",
    cidade: "Goianésia",
    preco: 1000000,
    quartos: 3,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/079/01.jpeg",
    fotos: ["images/imoveis/079/01.jpeg"],
    data: "",
    descricao: "Casa na Rua Itapaci, Granville, com 3 quartos e 1 banheiro."
  },
  {
    id: 80,
    titulo: "Um Terreno Á Venda – 03",
    tipo: "Lote",
    status: "Venda",
    localizacao: "GO 080 - Saída para Goiânia, do lado do Rancho Paraíso",
    cidade: "Goianésia",
    preco: 500000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/080/01.jpeg",
    fotos: ["images/imoveis/080/01.jpeg"],
    data: "",
    descricao: "Terreno na GO 080, saída para Goiânia, do lado do Rancho Paraíso. Excelente oportunidade."
  },
  {
    id: 81,
    titulo: "Casas Á Venda – Condomínio",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Condomínio Reserva da Serra",
    cidade: "Goianésia",
    preco: 255900,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/081/01.jpeg",
    fotos: ["images/imoveis/081/01.jpeg"],
    data: "",
    descricao: "Casas no Condomínio Reserva da Serra, com 3 quartos e 2 banheiros. Segurança e infraestrutura completa."
  },
  {
    id: 82,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua 12, nº 281, Centro",
    cidade: "Goianésia",
    preco: 500000,
    quartos: 3,
    banheiros: 2,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/082/01.jpeg",
    fotos: ["images/imoveis/082/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 12, nº 281, Centro, com 3 quartos e 2 banheiros. Localização central."
  },
  {
    id: 83,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua 19, nº 445-A - Setor Universitário",
    cidade: "Goianésia",
    preco: 1450000,
    quartos: 3,
    banheiros: 3,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/083/01.jpeg",
    fotos: ["images/imoveis/083/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 19, Setor Universitário, com 3 quartos e 3 banheiros. Alto padrão."
  },
  {
    id: 84,
    titulo: "Venda – Chácara",
    tipo: "Chácara",
    status: "Venda",
    localizacao: "Goianésia",
    cidade: "Goianésia",
    preco: 250000,
    quartos: 3,
    banheiros: 1,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/084/01.jpeg",
    fotos: ["images/imoveis/084/01.jpeg"],
    data: "",
    descricao: "Chácara em Goianésia, com 3 quartos e 1 banheiro. Ótima oportunidade."
  },
  {
    id: 85,
    titulo: "Venda – Casa",
    tipo: "Casa",
    status: "Venda",
    localizacao: "Rua 16a entre a 1 e santos Dumont - Palmeiras 3",
    cidade: "Goianésia",
    preco: 980000,
    quartos: 3,
    banheiros: 3,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/085/01.jpeg",
    fotos: ["images/imoveis/085/01.jpeg"],
    data: "",
    descricao: "Casa na Rua 16A, Palmeiras 3, com 3 quartos e 3 banheiros."
  },
  {
    id: 86,
    titulo: "Venda – Imóvel Comercial",
    tipo: "Comercial",
    status: "Venda",
    localizacao: "Em frente à praça do Carrilho - Do lado da estação rodoviária",
    cidade: "Goianésia",
    preco: 2200000,
    quartos: 31,
    banheiros: 8,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/086/01.jpeg",
    fotos: ["images/imoveis/086/01.jpeg"],
    data: "",
    descricao: "Imóvel comercial em frente à Praça do Carrilho, do lado da estação rodoviária. Grande estrutura com 31 quartos e 8 banheiros."
  },
  {
    id: 87,
    titulo: "Venda – Loteamento",
    tipo: "Lote",
    status: "Venda",
    localizacao: "Residencial Granville",
    cidade: "Goianésia",
    preco: 136000,
    quartos: 0,
    banheiros: 0,
    garagem: 0,
    area: 0,
    imagem: "images/imoveis/087/01.jpeg",
    fotos: ["images/imoveis/087/01.jpeg"],
    data: "",
    descricao: "Loteamento no Residencial Granville. Ótima oportunidade para investimento."
  }
];

const CONTATOS = {
  telefoneAluguel: "(62) 98507-0819",
  telefoneVendas: "(62) 98573-9405",
  telefoneVendas2: "(62) 98415-8065",
  whatsapp: "5562985070819",
  email: "contato@caetanoimoveis.com.br",
  endereco: "R. 29, 365 Centro - Goianésia - GO",
  horario: "07:30 - 17:00 (Seg-Sex)",
  instagram: "https://www.instagram.com/caetanoimoveisgoianesia/",
  facebook: "https://www.facebook.com/caetanoimoveisgoianesia",
  whatsappApi: "https://api.whatsapp.com/send/?phone=5562985070819&text&type=phone_number&app_absent=0"
};
